version: '3'
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: ./user-service/Dockerfile
    ports:
      - "5000:5000"
  product-service:
    build:
      context: ./product-service
      dockerfile: ./product-service/Dockerfile
    ports:
      - "3000:3000"
